apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  labels:  
    app: kuard
spec:
  type: NodePort
  selector:
    app: kuard
  ports:
  - name: http-metrics
    port: 80
    targetPort: 8080
    nodePort: 30007